apiVersion: v1
kind: LimitRange
metadata:
  name: lams-default-limits
  namespace: lams-prod
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 250m
        memory: 256Mi
      default:
        cpu: 500m
        memory: 512Mi
