apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: lams-prod
spec:
  selector:
    matchLabels: { app: elasticsearch }
  template:
    metadata:
      labels: { app: elasticsearch }
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
