apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: lams-prod
spec:
  selector:
    matchLabels: { app: rabbitmq }
  template:
    metadata:
      labels: { app: rabbitmq }
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.12-management
