apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: lams-prod
spec:
  selector:
    matchLabels: { app: redis }
  template:
    metadata:
      labels: { app: redis }
    spec:
      containers:
      - name: redis
        image: redis:7
