global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'lams-services'
    static_configs:
      - targets:
          - auth-service:8081
          - user-service:8082
          - asset-service:8083
          - request-service:8084
          - assignment-service:8085
          - maintenance-service:8086
          - notification-service:8087
          - audit-service:8088
