CREATE DATABASE IF NOT EXISTS lams_auth;
CREATE DATABASE IF NOT EXISTS lams_user;
CREATE DATABASE IF NOT EXISTS lams_asset;
CREATE DATABASE IF NOT EXISTS lams_request;
CREATE DATABASE IF NOT EXISTS lams_assignment;
CREATE DATABASE IF NOT EXISTS lams_maintenance;
CREATE DATABASE IF NOT EXISTS lams_notification;
CREATE DATABASE IF NOT EXISTS lams_audit;
